//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.AccesoDatos
{
    using Dominio.Modelo.Entidades;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TransporteDBEntities : DbContext
    {
        public TransporteDBEntities()
            : base("name=TransporteDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Estudiante> Estudiante { get; set; }
        public virtual DbSet<Historial> Historial { get; set; }
        public virtual DbSet<Reserva> Reserva { get; set; }
        public virtual DbSet<Ruta> Ruta { get; set; }
        public virtual DbSet<Vehiculo> Vehiculo { get; set; }
    }
}
