//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial
    {
        public int id_historial { get; set; }
        public Nullable<System.DateTime> fecha_reserva { get; set; }
        public Nullable<int> id_ruta { get; set; }
        public Nullable<int> id_estudiante { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Ruta Ruta { get; set; }
    }
}
